export const PREFIX = `BOARD`;

export const SET_EDIT_MODE = `${PREFIX}//SET_EDIT_MODE`;
export const RESET_EDIT_MODE = `${PREFIX}//RESET_EDIT_MODE`;

export const FETCH_GROUPS_REQUEST = `${PREFIX}//FETCH_GROUPS_REQUEST`;
export const FETCH_GROUPS_COMPLETED = `${PREFIX}//FETCH_GROUPS_COMPLETED`;
export const FETCH_GROUPS_FAILURE = `${PREFIX}//FETCH_GROUPS_FAILURE`;
export const SET_GROUP = `${PREFIX}//SET_GROUP`;
export const DELETE_GROUP = `${PREFIX}//DELETE_GROUP`;
export const CREATE_GROUP_REQUEST = `${PREFIX}//CREATE_GROUP`;
export const CREATE_GROUP_COMPLETED = `${PREFIX}//CREATE_GROUP_COMPLETED`;
export const CREATE_GROUP_FAILURE = `${PREFIX}//CREATE_GROUP_FAILURE`;
export const UPDATE_GROUP_REQUEST = `${PREFIX}//UPDATE_GROUP_REQUEST`;
export const UPDATE_GROUP_COMPLETED = `${PREFIX}//UPDATE_GROUP_COMPLETED`;
export const UPDATE_GROUP_FAILURE = `${PREFIX}//UPDATE_GROUP_FAILURE`;
export const UPDATE_GROUP = `${PREFIX}//UPDATE_GROUP`;
export const TOGGLE_ACTIVE_POINT = `${PREFIX}//TOGGLE_ACTIVE_POINT`;
export const PUSH_GROUP = `${PREFIX}//PUSH_GROUP`;
export const INSERT_TO_GROUP = `${PREFIX}//INSERT_TO_GROUP`;

export const SET_POINT = `${PREFIX}//SET_POINT`;
